train:
  max_fea_length: 10000
  max_seq_length: 320
  threshold: 1
  num_workers: 2
  batch_size: 1
  max_epochs: 200
  d_model: 512
  d_ff: 512
  d_vf: 1024
  num_heads: 4
  num_layers: 3
  dropout: 0.1
  weight_decay: 1.0e-5
  logit_layers: 3
  bos_idx: 0
  eos_idx: 0
  pad_idx: 0
  use_bn: 0
  drop_prob_lm: 0.5
  n_classes: 2
  sample_method: beam_search
  beam_size: 3
  temperature: 0.7
  sample_n: 1
  group_size: 1
  output_logsoftmax: 1
  decoding_constraint: 1
  suppress_UNK: 1
  block_trigrams: 1
  lr: 7.0e-05
  lr_patience: 7
  d_patch: 1536
  data_path_patch: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/REG_2025/train/20x_512px_0px_overlap/features_hoptimus1
  data_path_kb: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/REG_2025/train/20x_512px_0px_overlap/features_conch_v1
  bank_path: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/histai_processed/curated/conch/kb/memory_short.pt
  reports_json_path: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/REG_2025/reg_reports_splits.json
#  results_path: /lustre/nvwulf/home/sbsingh/reg/experiments
  model_load_path:
  model_type: wsi_caption
  devices: 8
  fast_dev_run: false
  num_folds: 3
  resume: false
  dataset_type: reg
  optim: AdamW
  amsgrad: true
  output_dir: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/results/neurips/wsi_caption/uni_v2/reg
  save_period: 1
  monitor_mode: max
  monitor_metric: BLEU_4
  early_stop: 20
  unused_params: true
  g_lambda: 0.07
  loss_type: nll
  epochs_val: 1
  start_val: 1
