train:
  max_fea_length: 10000
  max_seq_length: 320
  threshold: 1
  num_workers: 2
  batch_size: 1
  max_epochs: 200
  d_model: 768
  d_ff: 768
  d_vf: 768
  num_heads: 8
  num_layers: 3
  dropout: 0.2
  dropout_mlp: 0.4
  weight_decay: 1.0e-5
  logit_layers: 3
  bos_idx: 0
  eos_idx: 0
  pad_idx: 0
  use_bn: 0
  drop_prob_lm: 0.5
  sample_method: beam_search
  beam_size: 3
  temperature: 0.2
  sample_n: 1
  group_size: 1
  output_logsoftmax: 1
  decoding_constraint: 1
  suppress_UNK: 1
  block_trigrams: 1
  lr: 7.0e-05
  lr_patience: 3
  d_slide: 768
  d_patch: 768
  d_concept_deep: 512
  d_concept: 254
  data_path_slide: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/curated/slide_features_titan
  data_path_patch: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/curated/features_conch_v15
  data_path_concept: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/curated/gecko/v1/features
  reports_json_path: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/curated/tcga_reports_splits.json
  model_load_path:
  model_type: scout
  devices: 4
  fast_dev_run: false
  num_folds: 3
  resume: false
  dataset_type: reg
  optim: AdamW
  amsgrad: true
  save_period: 1
  monitor_mode: min
  monitor_metric: loss
  early_stop: 7
  unused_params: false
  output_dir: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/results/neurips/fresh/scout/conch/reg
  g_lambda: 0.01
  epochs_val: 1
  start_val: 1
